modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/WeightedInventory/issues"
license="MIT"

[[mods]]
modId="weightedinventory"
version="${file.jarVersion}"
displayName="Weighted Inventory"
displayURL="https://www.curseforge.com/minecraft/mc-mods/weighted-inventory"
authors="Mrbysco"
description='''
Unlock inventory slots based on your worn armor
'''

[[dependencies.weightedinventory]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="weightedinventory.mixins.json"